### ISSUE TITLE
Add upsert alias?

### ISSUE THREAD

**Issue by lukehorvat** [typicode/underscore-db#10]
Hi. The `insert` method behaves like what is usually called `upsert` in most DBMS'. So could you add `upsert` as an alias? I think it more clearly indicates intent.

Or, alternatively, rename the current `insert` method to `upsert`, and then rewrite `insert` to behave like a regular DBMS insert?

**Comment by typicode** [comment]
Hi @lukehorvat,

I agree `insert` would be better named `upsert`. What do you think should be the behaviour of `insert`?

**Comment by lukehorvat** [comment]
@typicode I would make `insert` throw an error if you try to insert a new item that has the same id as an existing item in the collection. In other words, the same behaviour as `INSERT INTO` SQL statements when a table has an id primary key.

**Comment by typicode** [comment]
Makes sense :) do you want to make a PR?

**Comment by lukehorvat** [comment]
@typicode 😎 👍
