### ISSUE TITLE
Using json-server as basic as you can, getting "hasOwnProperty" error

### ISSUE THREAD

**Issue by SatyaCOD** [typicode/underscore-db#12]
During AJAX post request, the first post works but any subsequent request is failing with the following error:
```
TypeError: doc.hasOwnProperty is not a function
```

I patched the issue on my local box by editing the following file, with the following fix:
underscore-db\src\index.js:36
```
if (doc[self.__id()] || doc.hasOwnProperty && doc.hasOwnProperty(self.__id())) {
```

My node version, may have something to do with it, I'm on 7 ... Other than that I can't think of why doing standard Object key checking solves my issue.

Here is my sample data from my json-server db.json file:
```
{
  "users":[
    {
      "username": "acker",
      "motto": "apple",
      "id": 14
    },
    {
      "username": "test3",
      "motto": "test33",
      "id": 15
    }
  ]
}
```

Again, very odd, the first communication with json-server to POST data works but no further POST requests to json-server works. I know json-server is NOT your package but editing underscore-db FIXED our issue locally.

Thank you kindly for any help you maybe able to offer.

**Comment by fras2560** [comment]
I am running into the same issue. I changed my node version from 7 to 5 and it worked. Did not work with 6 at all. I would be interested in the what the issue is.

**Comment by typicode** [comment]
I've updated `underscore-db` to use `_.has` instead.
There seem to be issues with `hasOwnProperty` and some versions of Node.

Can you try reinstalling JSON Server?

**Comment by SatyaCOD** [comment]
I reinstalled JSON Server. For now it is working fine. Thanks!

**Comment by typicode** [comment]
Great, thanks for the update :)
Lodash is so nice when it comes to making things work everywhere :D
